apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-prod-local
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  labels:
    codefresh.io/product: my-product
spec:
  project: default
  source:
    path: resources-prod
    repoURL: https://github.com/denis-codefresh/guestbook-local
    targetRevision: main
  destination:
    name: in-cluster
    namespace: test-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=true
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
